def is_work?
  return File.exist?("/Users/maisiebell/src/github.com/monzo")
end

brew "bat"
brew "chafa" # Generate ASCII images
brew "ctags"
brew "eza"
brew "fd" # Better find tools
brew "ffmpeg"
brew "fzf" # Fuzzy finder
brew "gh"
brew "git-lfs"
brew "glow"
brew "gnupg"
brew "htop"
brew "imagemagick"
brew "jq"
brew "lazygit"
brew "neovim"
brew "openapi"
brew "pinentry-mac"
brew "pkgconf"
brew "pngpaste"
brew "pyenv"
brew "pyenv-pip-migrate"
brew "reattach-to-user-namespace"
brew "ripgrep"
brew "rust"
brew "starship"
brew "stow"
brew "swig"
brew "tfenv"
brew "the_silver_searcher"
brew "tree"
brew "tree-sitter-cli"
brew "wget"
brew "yazi"
brew "yq"
brew "z"
brew "zoxide"
brew "zsh-history-substring-search"
brew "zsh-syntax-highlighting"
cask "font-fantasque-sans-mono-nerd-font"
cask "font-iosevka-nerd-font"
cask "kitty"

if is_work?
  tap "mdogan/zulu"
  cask "zulu-jdk21"
  brew "go@1.26"
end

unless is_work?
  brew "doctl" # DigitalOcean CLI
  brew "exiftool"  # Strip exif data from images
  brew "fnm"  # Better nvm
  brew "go"
  brew "golang-migrate"
  brew "lavat"
  brew "pass-cli"
  brew "postgresql@17", restart_service: :changed, link: true
  brew "postgis" # Geospatial data in postgresql
  brew "pre-commit"
  brew "r"
  brew "sqlc"
  brew "vdirsyncer", restart_service: :changed
  cask "1password"
  cask "1password-cli"
  cask "blender"
  cask "container"
  cask "calibre"
  cask "figma"
  cask "google-chrome"
  cask "keybase"
  # cask "mactex-no-gui"
  cask "obsidian"
  cask "quarto"
  cask "signal"
  cask "slicer"
  cask "vnc-viewer"
  cask "zoom"
  cask "font-stack-sans-text"
  cask "font-stack-sans-notch"
  cask "font-stack-sans-headline"
  cask "font-gohufont-nerd-font"
  brew "mpv"
  brew "yt-dlp"
  tap "protonpass/tap"
end
