- name: Setup Karakeep directory
  ansible.builtin.file:
    path: ~/karakeep
    state: directory
    mode: 0700

- name: Copy env file
  ansible.builtin.template:
    src: src/karakeep.env.j2
    dest: ~/karakeep/.env
    mode: 0600

- name: Copy podman-compose file
  ansible.builtin.copy:
    dest: ~/karakeep/docker-compose.yml
    src: src/karakeep-compose.yml

- name: Karakeep up
  ansible.builtin.command:
    cmd: podman-compose up -d
    chdir: "~/karakeep"
  changed_when: true
- name: Serve to Tailnet
  become: true
  ansible.builtin.shell: |
    tailscale serve --service=svc:links --https=443 --yes 3000
