- name: Apt update
  become: true
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade
  become: true
  apt:
    upgrade: full

- name: Ensure installed
  become: true
  apt:
    pkg:
      - git
      - neovim
      - podman
      - podman-compose
      - python3
      - pipx

- name: Ensure docker.io registry
  ansible.builtin.copy:
    dest: /etc/containers/registries.conf.d/docker.io.conf
    content: |
      unqualified-search-registries = ["docker.io"]
      [[registry]]
      location = "docker.io"
  become: true
- name: Pipx ensurepath
  become: true
  shell: pipx ensurepath --global
