- name: Install programs
  become: true
  apt:
    pkg:
      - acl
      - btop
      - prometheus-node-exporter

- name: Disable podman auto update
  become: true
  ansible.builtin.systemd:
    name: podman-auto-update.timer
    state: stopped
    enabled: false

- name: Ensure Node exporter env file
  become: true
  ansible.builtin.template:
    src: src/node-exporter-env.j2
    dest: /etc/default/prometheus-node-exporter

- name: Ensure app directory
  become: true
  ansible.builtin.file:
    path: /home/app/
    state: directory
    mode: 0755
