- name: Todo user present
  become: true
  ansible.builtin.user:
    name: todo
    shell: /bin/bash
  register: todo_user

- name: Ensure todo directory
  become: true
  ansible.builtin.file:
    path: /home/app/todo
    state: directory
    owner: todo
    group: todo
    mode: 0755

- name: Ensure todo directory
  become: true
  ansible.builtin.file:
    path: /home/app/todo/{{ item }}
    state: directory
    owner: todo
    group: todo
    mode: 0770
  with_items:
    - files
    - db

- name: Ensure config file
  become: true
  become_user: todo
  ansible.builtin.template:
    src: src/todo/config.yml.j2
    dest: /home/app/todo/config.yml
    mode: 0600
  register: config_file

- name: Ensure systemd definitions
  become: true
  ansible.builtin.copy:
    dest: "/etc/containers/systemd/users/{{ todo_user.uid }}"
    src: src/todo/systemd/
  register: systemd_files

- name: Enable Linger for todo user
  become: true
  ansible.builtin.command:
    argv:
      - /usr/bin/loginctl
      - enable-linger
      - "todo"
    creates: "/var/lib/systemd/linger/todo"

- name: Ensure secrets
  become: true
  become_user: todo
  containers.podman.podman_secret:
    state: present
    name: "{{ item.name }}"
    data: "{{ item.value }}"
  no_log: true
  with_items:
    - name: todo_db_passwd
      value: "{{ todo_db_passwd }}"
    - name: todo_jwtsecret
      value: "{{ todo_jwt_secret }}"

- name: Vikunja started
  become: true
  become_user: todo
  ansible.builtin.systemd_service:
    name: todo.service
    daemon_reload: true
    state: "{{ should_restart | ternary('restarted', 'started') }}"
    enabled: true
    scope: user
  vars:
    should_restart: "{{ systemd_files.changed or config_file.changed }}"

- name: Serve to Tailnet
  become: true
  ansible.builtin.shell: |
    tailscale serve --service=svc:todo --https=443 --yes localhost:3456
