- name: Tailscale
  hosts: all
  tags: [init]
  vars:
    tailscale_up_skip: yes
  roles:
    - role: artis3n.tailscale.machine
- name: Main
  hosts: all
  tasks:
    - name: Init
      ansible.builtin.include_tasks:
        file: tasks/init.yml
    - name: Git
      ansible.builtin.include_tasks:
        file: tasks/git.yml
- name: Home server packages
  hosts: optiflex
  tasks:
    - name: Init
      ansible.builtin.include_tasks:
        file: tasks/optiflex.yml
- name: Calibre-Web
  hosts: pi
  tasks:
    - name: Calibre Web
      ansible.builtin.include_tasks:
        file: tasks/calibre.yml
- name: linkwarden
  hosts: pi
  vars_files:
    - vault.yml
  tasks:
    - name: karakeep
      ansible.builtin.include_tasks:
        file: tasks/karakeep.yml

- name: todo
  hosts: optiflex
  vars_files:
    - vault.yml
  tasks:
    - name: todo (Vikunja)
      ansible.builtin.include_tasks:
        file: tasks/todo.yml

- name: Prometheus
  hosts: pi
  vars_files:
    - vault.yml
  tasks:
    - name: Prometheus
      ansible.builtin.include_tasks:
        file: tasks/prometheus.yml
