hide_window_decorations yes
background_opacity 0.8
background_blur 40

## SPLIT LAYOUT
# https://sw.kovidgoyal.net/kitty/layouts/#the-splits-layout
enabled_layouts splits,stack
map ctrl+a>ctrl+a send_key ctrl+a
map ctrl+a>_ launch --location=hsplit --cwd=current
map ctrl+a>- launch --location=vsplit --cwd=current
# navigation
map ctrl+a>h neighboring_window left
map ctrl+a>j neighboring_window down
map ctrl+a>k neighboring_window up
map ctrl+a>l neighboring_window right
# window movement
map ctrl+a>space layout_action rotate
map ctrl+a>shift+h move_window left
map ctrl+a>shift+j move_window down
map ctrl+a>shift+k move_window up
map ctrl+a>shift+l move_window right

# Shush.
enable_audio_bell no

# Tab bar
tab_bar_style powerline
tab_powerline_style round

cursor_trail 80

# font_family Jetbrains Mono NerdFont Nerd Font
font_family FantasqueSansM Nerd Font Mono
font_size 12.0
window_padding_width 5

map alt+left send_text all \x1b\x62
map alt+right send_text all \x1b\x66
map super+left send_text all \x1b\x62
map super+right send_text all \x1b\x66
map home send_text home
map end send_text end
map delete send_text delete

# Open new windows in same tab, in the same working directory.
map ctrl+shift+enter new_window_with_cwd
map cmd+enter new_window_with_cwd

map ctrl+shift+o launch --cwd=~/github.com/maisieccino/notes zsh -c 'nvim Home.md'
# BEGIN_KITTY_THEME
# Catppuccin Kitty Macchiato
include current-theme.conf
# END_KITTY_THEME

# OS-specific config
include ${KITTY_OS}.conf

allow_remote_control socket-only
listen_on unix:/tmp/kitty
shell_integration enabled
env read_from_shell=PATH LANG LC_* XDG_* EDITOR VISUAL

# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten $HOME/.local/share/nvim-kitty/site/pack/core/opt/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py --env NVIM_APPNAME=nvim-kitty
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output

## Sessions
map ctrl+a>shift+s save_as_session --use-foreground-process --relocatable
map ctrl+a>o goto_session sessions/notes.kitty-session
